/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package java大作业;

import java.awt.FlowLayout;
import java.awt.Image;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Vector;
import javax.swing.ButtonModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ZeroS
 */
public class Movieadd extends javax.swing.JFrame {
    /**
     * Creates new form Movieadd
     */
    public Movieadd() {
        initComponents();
        inittable();
    }
    public void inittable(){
        DefaultTableModel dtm1=(DefaultTableModel)jTable1.getModel();
        try {
            String sql="select * from Movie";
            ResultSet rs2=jdbc.queryBySql(sql);
            while(rs2.next()){
                Vector v=new Vector();
                v.add(rs2.getString(1));
                v.add(rs2.getString(2));
                v.add(rs2.getString(3));
                v.add(rs2.getString(4));
                v.add(rs2.getString(6));
                v.add(rs2.getString(7));
                v.add(rs2.getString(5));
                dtm1.addRow(v);
                } 
                rs2.close(); 
        }catch(Exception ex){
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "编号", "名称", "导演", "演员", "类型", "票价", "图片"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(5).setPreferredWidth(1);
        }

        jLabel1.setText("编号：");

        jLabel2.setText("名称：");

        jLabel3.setText("票价：");

        jLabel4.setText("演员：");

        jLabel5.setText("导演：");

        jLabel6.setText("类型：");

        b1.setText("《");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        b2.setText("》");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b3.setText("添加");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });

        jButton4.setText("删除");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        b5.setText("修改");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });

        b6.setText("添加图片");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });

        b7.setText("完成");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });

        jLabel8.setText("图片路径：");

        jButton1.setText("清除");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(18, 18, 18)
                                            .addComponent(t3))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGap(18, 18, 18)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18)
                                        .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(t4))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(t7)
                                .addGap(18, 18, 18)
                                .addComponent(b6)))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(t4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b6))
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        //函数getValueAt返回要查询的行和列处单元格的属性值
        this.t1.setText(dtm.getValueAt(row, 0).toString());
        this.t2.setText(dtm.getValueAt(row, 1).toString());
        this.t4.setText(dtm.getValueAt(row, 2).toString());
        this.t5.setText(dtm.getValueAt(row, 3).toString());
        this.t6.setText(dtm.getValueAt(row, 4).toString());
        this.t3.setText(dtm.getValueAt(row, 5).toString());
        this.t7.setText(dtm.getValueAt(row, 6).toString());
        ImageIcon icon=new ImageIcon(getClass().getResource("/java大作业/"+dtm.getValueAt(row, 6)));
        //icon=new ImageIcon(icon.getImage().getScaledInstance(getWidth(), getHeight()-25, Image.SCALE_DEFAULT));
        //jLabel7.setIcon(icon);
        jLabel7.setIcon(new ImageIcon(getClass().getResource("/java大作业/"+dtm.getValueAt(row, 6))));
    }//GEN-LAST:event_jTable1MouseClicked

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
         
        int row=jTable1.getSelectedRow();
        if(row>0){
        this.jTable1.setRowSelectionInterval(row-1,row-1);
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel(); 
        this.t1.setText(dtm.getValueAt(row-1, 0).toString());
        this.t2.setText(dtm.getValueAt(row-1, 1).toString());
        this.t4.setText(dtm.getValueAt(row-1, 2).toString());
        this.t5.setText(dtm.getValueAt(row-1, 3).toString());
        this.t6.setText(dtm.getValueAt(row-1, 4).toString());
        this.t3.setText(dtm.getValueAt(row-1, 5).toString());
        this.t7.setText(dtm.getValueAt(row-1, 6).toString());
        jLabel7.setIcon(new ImageIcon(getClass().getResource("/java大作业/"+dtm.getValueAt(row-1, 6))));
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        
        int row=this.jTable1.getSelectedRow();
        if(row<this.jTable1.getRowCount()-1){
        this.jTable1.setRowSelectionInterval(row+1,row+1);
        DefaultTableModel dtm=(DefaultTableModel)jTable1.getModel();
        this.t1.setText(dtm.getValueAt(row+1, 0).toString());
        this.t2.setText(dtm.getValueAt(row+1, 1).toString());
        this.t4.setText(dtm.getValueAt(row+1, 2).toString());
        this.t5.setText(dtm.getValueAt(row+1, 3).toString());
        this.t6.setText(dtm.getValueAt(row+1, 4).toString());
        this.t3.setText(dtm.getValueAt(row+1, 5).toString());
        this.t7.setText(dtm.getValueAt(row+1, 6).toString());
        jLabel7.setIcon(new ImageIcon(getClass().getResource("/java大作业/"+dtm.getValueAt(row+1, 6))));
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        // TODO add your handling code here:
        JFileChooser jfc=new JFileChooser();  
        jfc.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES ); 
        jfc.showOpenDialog(jfc);
        File file=jfc.getSelectedFile();  
        if(file.isFile()){  
            //System.out.println("文件:"+file.getPath());  
            try{
			//先创建File类对象
			File file1=new File(file.getPath());
			//构造输入流对象
			FileInputStream fis=new FileInputStream(file1);
			DataInputStream dis=new DataInputStream(fis);
			
			//构造输出流对象
			File file2=new File("src/java大作业/"+file.getName());
			FileOutputStream fos=new FileOutputStream(file2);
			DataOutputStream dos=new DataOutputStream(fos);
			//读写
			int temp;
			while((temp=dis.read())!=-1){
				dos.write(temp);
			}
			//关闭
			dis.close();
			fis.close();
			dos.close();
			fos.close();
			System.out.println("文件复制成功!");
                        this.t7.setText(file.getName());
                        this.jLabel7.setIcon(new ImageIcon(getClass().getResource(file.getName())));
		}catch(FileNotFoundException ex){
			System.out.println("文件不存在！");
		}catch(IOException ex){
			System.out.println("读写异常:");
			ex.printStackTrace();
		}
	}
      
        
    }//GEN-LAST:event_b6ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        boolean flag = true;
        int row = 0;
        String MovId=this.t1.getText();
        while(row<this.jTable1.getRowCount()){  
            if(MovId.equalsIgnoreCase(dtm.getValueAt(row,0).toString())){
                JOptionPane.showMessageDialog(this, "添加失败，编号重复", "警告框", JOptionPane.INFORMATION_MESSAGE);//弹出警告框
                flag=false;
                break;
            }
            row++;
        }
        String status=null;
        if(flag){
        String sql="INSERT INTO MOVIE Values('"+t1.getText()+"','"+t2.getText()+"','"+t4.getText()+"','"+t5.getText()+"','"+t7.getText()+"','"+t6.getText()+"','"+t3.getText()+"')";
                try {
                    jdbc.modifyBySql(sql);
                } catch (Exception ex) {

                }    
        Vector v = new Vector();
        v.add(this.t1.getText());
        v.add(this.t2.getText());
        v.add(this.t4.getText());
        v.add(this.t5.getText());
        v.add(this.t6.getText());
        v.add(this.t3.getText());
        v.add(this.t7.getText());
        v.add(status);
        dtm.addRow(v);
        JOptionPane.showMessageDialog(this, "添加成功", "提示框", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int i=JOptionPane.showConfirmDialog(null, "确定删除吗？", "删除确认", JOptionPane.YES_NO_OPTION);
        //0--是，1--否 
        try {
        if(i==0){
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
            int row = jTable1.getSelectedRow();
            String sql="DELETE FROM Movie WHERE MovID='"+dtm.getValueAt(row, 0).toString()+"'";
                   
            jdbc.modifyBySql(sql);
                    
            dtm.removeRow(row);
            this.t1.setText(null);
            this.t2.setText(null);
            this.t3.setText(null);
            this.t4.setText(null);
            this.t5.setText(null);
            this.t6.setText(null);
            this.t7.setText(null);
            this.jLabel7.setIcon(null);
        }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "删除前请清除场次信息", "出错啦", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.t1.setText(null);
        this.t2.setText(null);
        this.t3.setText(null);
        this.t4.setText(null);
        this.t5.setText(null);
        this.t6.setText(null);
        this.t7.setText(null);
        this.jLabel7.setIcon(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
        int row=0,nrow=jTable1.getSelectedRow();
        boolean flag=true;
        String id=dtm.getValueAt(jTable1.getSelectedRow(), 0).toString();
        
        if(t1.getText().equals("")){
            JOptionPane.showMessageDialog(this, "修改失败,空ID", "警告框", JOptionPane.ERROR_MESSAGE);
        }else{
            while (row < this.jTable1.getRowCount()) {
                
                if(nrow==row){
                    row++;
                    continue;
                }
                if (t1.getText().equalsIgnoreCase(dtm.getValueAt(row, 0).toString())) {
                    JOptionPane.showMessageDialog(this, "修改失败，编号重复", "警告框", JOptionPane.ERROR_MESSAGE);
                    flag = false;
                    break;
                }
                row++; 
                
            }
        }
        if(flag){
            row = jTable1.getSelectedRow();
            String sql="UPDATE Movie SET MovID='"+t1.getText()+"',MovName='"+t2.getText()+"',Director='"+t4.getText()+"',MainAct='"+t5.getText()+"',MovPoster='"+t7.getText()+"',"
                + "MovType='"+t6.getText()+"',prince='"+t3.getText()+"' WHERE MovID='"+dtm.getValueAt(row, 0).toString()+"'";
                try {
                    jdbc.modifyBySql(sql);
                } catch (Exception ex) {

                }
            dtm.setValueAt(this.t1.getText(), row, 0);
            dtm.setValueAt(this.t2.getText(), row, 1);
            dtm.setValueAt(this.t4.getText(), row, 2);
            dtm.setValueAt(this.t5.getText(), row, 3);
            dtm.setValueAt(this.t6.getText(), row, 4);
            dtm.setValueAt(this.t3.getText(), row, 5);
            dtm.setValueAt(this.t7.getText(), row, 6);
            JOptionPane.showMessageDialog(this, "修改成功", "提示框", JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_b5ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        // TODO add your handling code here:
        dispose();
        Admin adminFrame= new Admin();
        adminFrame.setVisible(true);
    }//GEN-LAST:event_b7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Movieadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Movieadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Movieadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Movieadd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Movieadd().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    // End of variables declaration//GEN-END:variables
}
